import { type NextPage } from "next";
import { useState } from "react";
import Head from "next/head";

import { api } from "../utils/api";
import Modal from "../components/Modal";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  const [showModal, setShowModal] = useState(true);

  return (
    <>
      <Head>
        <title>Hataw Takbo</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Modal
          title="Modal Title"
          onClose={() => {
            setShowModal(false);
          }}
          show={showModal}
        >
          .
        </Modal>
      </main>
    </>
  );
};

export default Home;
